# UAS PEMBELAJARAN MESIN 
### Nama : Hafizh Hilman Asyhari
### NIM : 202331206
### Kelas : D
### Mata Kuliah : Pembelajaran Mesin 
### Q Learning
### Program Studi : S1 Teknik Informatika 
### Fakultas : Fakultas Telematika Energi
#### 2024-2025

In [16]:
import numpy as np
import random

# Definisikan keadaan dan tindakan
states = ["state1", "state2", "state3", "state4"]
actions = ["action1", "action2", "action3"]
n_states = len(states)
n_actions = len(actions)

- states = ["state1", "state2", "state3", "state4"]:

- Definisi Keadaan: Menyusun daftar states, yang menunjukkan berbagai kemungkinan keadaan dalam lingkungan yang ingin dipelajari oleh agen. Dalam hal ini, terdapat 4 keadaan yang disimulasikan.
- actions = ["action1", "action2", "action3"]:

- Definisi Tindakan: Menyusun daftar actions, yang mencakup berbagai tindakan yang dapat diambil agen pada setiap keadaan. Di sini, ada 3 pilihan tindakan yang tersedia.
- n_states = len(states) dan n_actions = len(actions):

- Menentukan Jumlah Keadaan dan Tindakan: n_states dan n_actions menyimpan jumlah keadaan dan tindakan, yang akan digunakan untuk menentukan ukuran tabel Q.

In [6]:
# Inisialisasi tabel Q
Q = np.zeros((n_states, n_actions))

# Parameter Q-Learning
alpha = 0.1  # learning rate
gamma = 0.9  # discount factor
epsilon = 0.2  # epsilon-greedy

Q = np.zeros((n_states, n_actions)):

Inisialisasi tabel Q: Membuat sebuah matriks Q dengan ukuran n_states x n_actions, yang diisi dengan angka nol. Matriks ini akan menyimpan nilai Q untuk setiap pasangan keadaan dan tindakan.
Parameter Q-Learning:

alpha = 0.1: Learning rate yang mengontrol seberapa besar kontribusi nilai baru dalam pembaruan tabel Q.
gamma = 0.9: Discount factor yang mengontrol seberapa banyak agen mempertimbangkan masa depan dalam pemilihan tindakan.
epsilon = 0.2: Epsilon-greedy, yang menentukan kemungkinan agen untuk memilih tindakan secara acak (eksplorasi) dibandingkan memilih tindakan berdasarkan nilai Q (eksploitasi).

In [8]:
# Reward matrix (misalnya berdasarkan dataset)
rewards = {
    "state1": [1, -1, 0],
    "state2": [0, 2, -1],
    "state3": [-1, 0, 3],
    "state4": [1, 0, 0]
}


rewards = { ... }:
Matriks Reward: rewards adalah sebuah dictionary yang menyimpan nilai reward untuk setiap kombinasi keadaan dan tindakan. Setiap keadaan (misalnya state1, state2, dll) memiliki sebuah daftar yang berisi nilai reward terkait untuk tindakan yang tersedia (misalnya action1, action2, action3).
Nilai dalam matriks ini mencerminkan seberapa baik atau buruk suatu tindakan diambil dalam keadaan tertentu, yang membantu agen untuk mempelajari strategi optimal.

In [10]:
# Fungsi untuk memilih aksi berdasarkan epsilon-greedy
def choose_action(state_index):
    if random.uniform(0, 1) < epsilon:
        # Eksplorasi: pilih tindakan acak
        return random.choice(range(n_actions))
    else:
        # Eksploitasi: pilih tindakan dengan nilai Q tertinggi
        return np.argmax(Q[state_index])


Fungsi choose_action(state_index):
Fungsi ini digunakan untuk memilih tindakan berdasarkan strategi epsilon-greedy, yang bertujuan untuk menjaga keseimbangan antara eksplorasi dan eksploitasi dalam Q-Learning.
Eksplorasi: Dengan probabilitas epsilon, agen memilih tindakan secara acak, memungkinkan untuk menjelajahi tindakan yang belum pernah dicoba sebelumnya.
Eksploitasi: Dengan probabilitas 1 - epsilon, agen memilih tindakan yang telah memberikan reward tertinggi berdasarkan tabel Q.

In [22]:
# Proses Q-Learning
for episode in range(1000):  # iterasi episode
    state_index = random.choice(range(n_states))  # pilih keadaan acak
    done = False
    
    while not done:
        action_index = choose_action(state_index)  # pilih tindakan berdasarkan Q
        reward = rewards[states[state_index]][action_index]  # reward dari lingkungan
        next_state_index = (state_index + 1) % n_states  # pindah ke keadaan berikutnya (misalnya sederhana)
        
        # Pembaruan tabel Q
        Q[state_index, action_index] = Q[state_index, action_index] + alpha * \
            (reward + gamma * np.max(Q[next_state_index]) - Q[state_index, action_index])
        
        state_index = next_state_index  # update state ke state berikutnya

        if state_index == 0:  # Misalnya episode berhenti setelah kembali ke state1
            done = True

Iterasi Episode:

for episode in range(1000): mengulang proses Q-Learning selama 1000 episode.
Inisialisasi Keadaan:

state_index = random.choice(range(n_states)) memilih keadaan awal secara acak dari daftar keadaan yang ada.
Pemilihan Tindakan:

action_index = choose_action(state_index) memilih tindakan berdasarkan strategi epsilon-greedy.
Menghitung Reward:

reward = rewards[states[state_index]][action_index] menghitung reward yang diperoleh berdasarkan keadaan dan tindakan yang dipilih.
Pindah ke Keadaan Berikutnya:

next_state_index = (state_index + 1) % n_states menentukan keadaan berikutnya dengan langkah sederhana (modulo n_states).
Pembaruan Tabel Q:

Q[state_index, action_index] = Q[state_index, action_index] + alpha * (reward + gamma * np.max(Q[next_state_index]) - Q[state_index, action_index])
Pembaruan nilai Q berdasarkan rumus Q-Learning dengan memperhitungkan reward dan nilai Q dari keadaan berikutnya.
Update Keadaan:

state_index = next_state_index memperbarui keadaan saat ini menjadi keadaan berikutnya.
Menentukan Akhir Episode:

if state_index == 0: episode selesai jika kembali ke keadaan pertama (misalnya state1).

In [14]:
# Cetak tabel Q setelah pembaruan
print("Tabel Q setelah pembaruan:")
print(Q)

Tabel Q setelah pembaruan:
[[12.78121884  7.09418862  7.21661682]
 [12.15616195 14.21525156 10.9383129 ]
 [ 9.18388938 10.07108208 14.01156871]
 [12.44512138 10.30895322 10.51357429]]


### Cetak tabel Q setelah pembaruan: Komentar ini menjelaskan tujuan dari baris kode berikutnya, yaitu untuk menampilkan hasil pembaruan tabel Q setelah proses pembelajaran Q-Learning.
Mencetak Tabel Q:

print("Tabel Q setelah pembaruan:"): Menampilkan teks yang memberi tahu pengguna bahwa tabel Q yang baru saja diperbarui akan ditampilkan.
print(Q): Menampilkan isi tabel Q yang telah diperbarui selama proses Q-Learning, yang berisi nilai-nilai Q yang diperoleh untuk setiap pasangan (keadaan, tindakan).